"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("./../controllers/auth");
const router = (0, express_1.Router)();
router.post('/send-otp', auth_1.sendOtp);
router.put('/verify-otp', auth_1.veifyOtp);
router.get('/current-user', auth_1.currentUser);
router.get('/sign-out', auth_1.signOut);
exports.default = router;
