name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint:fix
      - run: npm run lint
      - run: npx prisma generate
      - run: npx prisma migrate deploy

      - run: npm run test
